{
 "title": "Logs Dashboard",
 "description": "Container/Pod Log Dashboard(Loki as DataSource)",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "stream",
    "label": "Stream",
    "query": {}
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "err" },
   { "name": "DS_LOKI", "label": "Datasource", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": {}
   },
   {
    "name": "time_range",
    "label": "Time range",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs for `$job`",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({job=~\"$job\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of `$searchable_pattern`",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({job=~\"$job\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{job=~\"$job\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  },
  {
   "title": "Total count grouped by jobs in last $time_range",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "short",
   "valueName": "total",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (count_over_time({job=\"apachelogs\"} [$time_range]) or count_over_time({job=\"containerlogs\"} [$time_range]) or count_over_time({job=\"syslogs\"} [$time_range]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Apache Method Pie",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 12 },
   "format": "short",
   "valueName": "total",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"apachelogs\"} | pattern `<_> - - <_> \"<method> <_> <_>\" <_> <_> <_> \"<_>\" \"<_>\"`)[$time_range])) by (method)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Count of container logs historical",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({job=\"containerlogs\"})[$__interval])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}